version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          _JAVA_OPTIONS: "-Xmx1G -Xms256M -Xss2M"
    steps:
      - checkout
      - restore_cache:
          key: ika-projects-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ checksum "build.sbt" }}
      - run: sbt update
      - save_cache:
          key: ika-projects-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ checksum "build.sbt" }}
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2
      - run: sbt test:compile test
      - run: sbt clean dist
      - persist_to_workspace:
          root: .
          paths:
            - target

  ansible:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - run: sudo apt-get install libyaml-dev
      - run: sudo pip install ansible ansible-lint==3.4.23
      - run: ansible --version
      - run: ansible-lint --version
      - run: cd ansible && echo "${ANSIBLE_VAULT_PASS}" > ansible_vault.txt
      - run: cd ansible && ansible-lint site.yml
      - run: cd ansible && ansible-playbook -i "localhost," site.yml --syntax-check --vault-password-file ansible_vault.txt

  deploy:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "95:39:37:25:ca:90:c7:22:02:03:74:46:2d:a5:41:13"

      - run: git --version
      - run: ssh -A ${HOST_NAME} -l${USER_NAME} -p6528 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "mkdir -p /root/ika/target/universal"
      - run: scp -P6528 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/universal/ika-0.1.0-SNAPSHOT.zip ${USER_NAME}@${HOST_NAME}:/root/ika/target/universal/ika-0.1.0-SNAPSHOT.zip
      - run: echo "${ANSIBLE_VAULT_PASS}" > ansible_vault.txt
      - run: scp -P6528 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ansible_vault.txt ${USER_NAME}@${HOST_NAME}:/root/ika/ansible/ansible_vault.txt
      - run: ssh -A ${HOST_NAME} -l${USER_NAME} -p6528 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "cd /root/ika && git pull && cd ansible && ansible-playbook -i inventory/hosts site.yml --vault-password-file ansible_vault.txt"

workflows:
  version: 2
  run_all:
    jobs:
      - build
      - ansible
      - deploy:
          requires:
            - build
            - ansible
          filters:
            branches:
              only: master
